### PR TITLE
Removed $ModLoad imfile from rsyslog_file_input resource

### LINKED ISSUE #119: file_input template includes imfile, so cannot by reused
### Cookbook version
4.0.1
### Chef-client version
12.15.19

### Platform Details
Ubuntu 16.04 on AWS

### Scenario:
Can't call the `file_input` resource multiple times with the default template. The config test added in 4.0.1 will fail b/c imfile is included multiple times.

### Steps to Reproduce:
Create multiple `ryslog_file_input` resources using the default template.

### Expected Result:
Successful converge.

### Actual Result:
```
[2016-11-02T21:03:43+00:00] ERROR: Exception handlers complete
ERROR: execute[validate_config] (rsyslog::default line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of rsyslogd -N 1 -f /etc/rsyslog.conf ----
STDOUT:
rsyslogd: version 8.16.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: module 'imfile' already in this config, cannot be added  [v8.16.0 try http://www.rsyslog.com/e/2221 ]
rsyslogd: module 'imfile' already in this config, cannot be added  [v8.16.0 try http://www.rsyslog.com/e/2221 ]
---- End output of rsyslogd -N 1 -f /etc/rsyslog.conf ----
Ran rsyslogd -N 1 -f /etc/rsyslog.conf returned 1
[2016-11-02T21:03:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The input_file template included in the cookbook should not include imfile or should have some conditional logic to ensure it's only included in one of them. It might make sense to have a dedicated file in `/etc/rsyslog.d` to include `imfile` that is created anytime the `ryslog_file_input` resource is used.

### PR DESCRIPTION
**Pull request by runswithd6s**
In order use the `rsyslog_file_input` resource, `$ModLoad imfile` needs to be
defined only once. Removed it from the `file-input.conf.erb` template file and
added `README.md` instructions to add the `imfile` module to the node to enable.
Added tests for a second log file and for existence of one module load
statement.

### Description

The file_input resource was incorrectly including the legacy `$ModLoad imfile`
declaration in each new config file created from template. Additionally, the
legacy style script prevented newer rsyslog daemons from using `inotify` method.
This commit adds:

  - Legacy configuration file support
  - Ranier style configuration file support
  - Ability to specify imfile module parameters
  - Ability to specify additional resource parameters for `rsyslog_file_input`

### Issues Resolved

Fixed #119.

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by runswithd6s** [comment]
As simple as this approach is to implement, it's not simple to test. When overriding node attributes in `kitchen.yml`, I get conflicting states for CentOS 6 and CentOS 7 hosts (or really the difference between hosts that use `imklog` and those that use `imjournal`). To make testing easier, and also introduce Rainer script for specifying `imfile` attributes, I'm going to introduce a new node attribute: `use_imfile`.

**Comment by runswithd6s** [comment]
(Note: there are some SmartOS failures that should probably get fixed outside the scope of this PR.)

**Comment by runswithd6s** [comment]
@tas50, @jtimberman This pull request is ready for review. All tests are passing, and DCO signed-off-by is completed. Please let me know if you'd like anything changed.

**Comment by runswithd6s** [comment]
@tas50, @jtimberman I took out the feature-flag requirement for this update and instead built the `35-imfile.conf` template whenever the `rsyslog_file_input` resource was defined. This makes the integration simpler and behave as one would expect. Are either of you ready for a code-review?

**Comment by Vasu1105** [comment]
@tas50 I have verified this PR from my side and it LGTM.

**Comment by Vasu1105** [comment]
@runswithd6s you need to reabse this branch.

**Comment by runswithd6s** [comment]
@Vasu1105 I can close this one and re-open from a personal fork https://github.com/runswithd6s/chef-rsyslog/tree/bug-119-too_many_imfiles.

**Comment by Vasu1105** [comment]
> @Vasu1105 I can close this one and re-open from a personal fork https://github.com/runswithd6s/chef-rsyslog/tree/bug-119-too_many_imfiles.

Yes, I think you can do that.

**Comment by runswithd6s** [comment]
Closing. Re-opened as squashed commit in #161

**Pull request closed without merging**
