### PR TITLE
Update to use library for finding remote servers

### PR DESCRIPTION
**Pull request by spion06**

### CODE REVIEW

**Comment by tas50** [comment]
Sorry for the late response.  Is there a particular reason for moving this code into a library?

**Comment by spion06** [comment]
I have a use-case where I need to forward auditd events though rsyslog and not have them go to a file since auditd is already sending these logs to a file. currently i'm replicating the search code in my cookbook. Here's what my config looks like in rsyslog.d 

```
$ActionQueueType LinkedList # use asynchronous processing
$ActionQueueFileName srvrfwd # set file name, also enables disk mode
$ActionResumeRetryCount -1 # infinite retries on insert failure
$ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down
$SystemLogRateLimitInterval 0

if $programname == 'audispd' then @rsyslog_server
& ~
```

**Comment by tas50** [comment]
With the removal of chef-solo support this is all going to get reworked in the near future.

**Comment by spion06** [comment]
thanks for the update. Should I assume I need to continue to implement my own search function for my use-case or will that be resolved with the rework?

**Pull request closed without merging**
