### PR TITLE
[COOK-4228] Enable dual protocol server

### PR DESCRIPTION
**Pull request by groknix**
Enables dual protocol server and cleans up
rsyslog.conf.

https://tickets.opscode.com/browse/COOK-4228

### CODE REVIEW

**Comment by bewiwi** [comment]
This PR can be realy usefull.  UP !!

**Comment by tas50** [comment]
Care to rebase this against the current changes?  Also please sign the CLA.  I'd love to merge this change.  Seems like a pretty standard use case.

**Comment by troyready** [comment]
We put together a similar implementation in 2013 and never got around to making a PR for it. I've consolidated it to one PR at https://github.com/biola/rsyslog/tree/bothprotos if that implementation would work (I could open a new PR for it, or feel free to cherry-pick the commit)

**Comment by tas50** [comment]
I'm closing this out now since it's been a year and the CLA is not signed. Feel free to open it back up if the CLA is signed.

**Pull request closed without merging**
